### ISSUE TITLE
Home page form text colour is incorrect

### ISSUE THREAD

**Issue by thinisde** [SashenJayathilaka/NETFLIX-Clone#36]
The colour is white, so you don't see anything

Edge, System mode is on dark mode

![image](https://user-images.githubusercontent.com/51492960/211908301-8bc27c5a-06d1-4103-b97e-5fa1886ea639.png)

![image](https://user-images.githubusercontent.com/51492960/211908346-41ac2b1a-e233-4c79-a26c-56eb87e7156b.png)

**Comment by SashenJayathilaka** [comment]
**Yes, It's My mistake. Now, this mistake fixed.**
